### ISSUE TITLE
slow json GET in curl::curl_fetch_memory comparing to curl::curl_download

### ISSUE THREAD

**Issue by alexdeng** [hadley/httr#268] opened 2015-08-07 00:41 UTC
I have a query that is getting a 120m large json response. Using httr::GET this is currently very slow. Through debug I found curl_fetch_download is the problem and when I use curl_download and then read the file the function is much faster. You can see the system.time below. Note that 30s is elapsed on the fromJSON step, therefore httr::GET in this case took about 230s while using curl_download only took about 30s (ignoring disk I/O). 

> system.time({tmp = getJSON(url)})
   user  system elapsed 
 153.38   85.45  261.41 
> system.time({tmp2 = getJSON2(url)})
   user  system elapsed 
  38.64    0.83   61.64 

I'm using httr_1.0.0 with curl_0.9.1 on windows. 
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 x64 (build 9200)

-----------------
#' get JSON response from url
#' @param url url
#' @param query
#' @param ... parameters passed on to fromJSON
#' @export
getJSON <- function(url,query=NULL, ...){
    auth = get_auth()
    fullurl = url_append(url,query)
    txt = httr::GET(fullurl, auth)
    httr::stop_for_status(txt)
    jsonlite::fromJSON(httr::content(txt,'text'),...)
}

getJSON2 <- function(url,query=NULL, ...){
    auth = get_auth()
    fullurl = url_append(url,query)
    h = curl::new_handle()
    curl::handle_setopt(h, .list = auth$options)
    tmp = curl::curl_download(fullurl,tempfile(),handle=h)
    jsonlite::fromJSON(tmp,...)
}

**Comment by alexdeng** [comment] 2015-08-07 00:42
typo correction,  curl_fetch_memory is the problem.

**Comment by jeroenooms** [comment] 2015-08-07 13:14
Hey Alex. Can you try to rule out the server side? I am testing this from localhost, and can't reproduce the problem. Downloading a 100mb file:

```r
test <- "http://localhost/100MBtest.bin"
system.time(curl_download(test, tempfile(), handle = new_handle(verbose = T)))
#   user  system elapsed 
#  0.031   0.211   0.284

system.time(curl_fetch_memory(test, handle = new_handle(verbose = T)))
#   user  system elapsed 
#  0.098   0.094   0.196
```

Can you show us the breakdown of the timings from your example with `curl_fetch_memory`:

```r
req <- curl_fetch_memory(fullurl, handle = new_handle(verbose = T))
print(req$times)
```

That helps to narrow down if the extra time is spent initiating the connection or in the SSL handshake or so. Also ensure that both connections use the same gzip compression settings for fair comparison.

**Comment by alexdeng** [comment] 2015-08-07 16:41
Here is the time of my curl_fetch_memory.  I'm certain the server side has gzip compression. You can see the header bellow.  But assume curl_download is fast, I'm curious why curl_fetch_memory has problem. 

> print(req$times)
     redirect    namelookup       connect   pretransfer starttransfer 
        0.062         0.000         0.000         0.000        23.532 
        total 
      187.375 


curl::parse_headers(req$headers)
 [1] "HTTP/1.1 200 OK"                              
 [2] "Cache-Control: private"                       
 [3] "Content-Type: application/json; charset=utf-8"
 [4] "Content-Encoding: gzip"                       
 [5] "Vary: Accept"                                 
 [6] "Server: Microsoft-IIS/8.5"                    
 [7] "X-AspNet-Version: 4.0.30319"                  
 [8] "Persistent-Auth: true"                        
 [9] "X-Powered-By: ASP.NET"                        
[10] "Date: Fri, 07 Aug 2015 16:31:44 GMT"          
[11] "Content-Length: 11566137"

**Comment by alexdeng** [comment] 2015-08-07 16:45
Here is the same query using curl_fetch_disk, this time it was much faster

> req2 <- curl::curl_fetch_disk(fullurl, tempfile(),handle = handle)
> print(req2$times)
     redirect    namelookup       connect   pretransfer starttransfer 
        0.000         0.000         0.000         0.000        14.110 
        total 
       15.094

**Comment by jeroenooms** [comment] 2015-08-07 18:12
You're right, `curl_fetch_memory` is relatively slow in windows. Perhaps its due to using `realloc` which apparently is [poorly implemented in windows](https://blog.kowalczyk.info/article/2be/realloc-on-Windows-vs-Linux.html). I'll investigate, thanks for reporting.

**Comment by alexdeng** [comment] 2015-08-07 18:52
Thanks Jeroen! This one was puzzled me for a while. On a site note, RCurl::getURL isn't very slow so there might lie the fix. 
> system.time({req = RCurl::getURI(fullurl, userpwd = get_auth()$options$userpwd, httpauth=8L)})
   user  system elapsed 
  18.62    0.64   38.79

**Comment by jeroenooms** [comment] 2015-08-07 19:06
I pushed a [fix](https://github.com/jeroenooms/curl/commit/33c59ed017c9d2710b050ad4518a5743ec9944dd) to curl, can you check if this works? If this fixes it for windows, it still needs further testing to see if this negatively affects performance other platforms, in which case we'll have to `#ifdef _win32`.

Heads up that you cannot use devtools on windows to install `curl` because devtools itself uses curl so the dll is locked. You need to manually git clone and install `curl`, either from the command line or via rstudio or so.

**Comment by alexdeng** [comment] 2015-08-07 19:46
ok This fix worked. Now the performance is reasonable
req <- curl::curl_fetch_memory(fullurl, handle = handle)
> print(req$times)
     redirect    namelookup       connect   pretransfer starttransfer         total 
        0.016         0.000         0.000         0.000        13.140        14.188

**Comment by jeroenooms** [comment] 2015-08-07 19:49
While you're at it, can you test the new `ie_proxy_info` and `ie_get_proxy_for_url` settings? See also this gist: https://gist.github.com/jeroenooms/1250e73f93acfffb0e9a

**Comment by alexdeng** [comment] 2015-08-07 20:22
Got error from Test 2. 

> library(curl)> ie_proxy_info()$AutoDetect[1] TRUE
$AutoConfigUrlNULL
$ProxyNULL
$ProxyBypassNULL
> ie_get_proxy_for_url("http://www.google.com/test")Error in ie_get_proxy_for_url("http://www.google.com/test") :   STRING_ELT() can only be applied to a 'character vector', not a 'NULL'> connect_with_proxy <- function(url){+     proxy_server <- ie_get_proxy_for_url(url)+     h <- new_handle(verbose = TRUE, proxy = proxy_server)+     readLines(curl(url, handle = h))+ }> > connect_with_proxy("http://httpbin.org/get")Error in ie_get_proxy_for_url(url) :   STRING_ELT() can only be applied to a 'character vector', not a 'NULL'> 
EnvironmentHistoryBuildGit
	Build & Reload		Check		More

Alex(Shaojie) Deng

Date: Fri, 7 Aug 2015 12:49:56 -0700

**Comment by jeroenooms** [comment] 2015-08-07 20:46
Thanks! I pushed a fix for that case. Could you try one more time to reinstall curl from github and run:

```r
ie_get_proxy_for_url("http://www.google.com/test")
ie_get_proxy_for_url("http://localhost/test")
ie_get_proxy_for_url("http://foo/test")
```

**Comment by alexdeng** [comment] 2015-08-07 22:48
> ie_get_proxy_for_url("http://www.google.com/test")NULL> ie_get_proxy_for_url("http://localhost/test")NULL> ie_get_proxy_for_url("http://foo/test")NULL
Alex(Shaojie) Deng

Date: Fri, 7 Aug 2015 13:46:33 -0700

**Comment by jeroenooms** [comment] 2015-08-08 08:52
Okay I guess you're not using a proxy :) 

I think this issue can be closed now.

**Comment by jeroenooms** [comment] 2015-08-08 11:23
@alexdeng this fix is on CRAN now. After the weekend you should be able to install the new windows builds from CRAN.

**Closed** 2015-12-17 17:03 UTC
